// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using apicsharpfacturas.Data;

#nullable disable

namespace apicsharpfacturas.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240910200510_initial_migration")]
    partial class initial_migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("apicsharpfacturas.Models.ClientEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("lastnames")
                        .HasColumnType("longtext");

                    b.Property<string>("names")
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("clients");
                });

            modelBuilder.Entity("apicsharpfacturas.Models.Product", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ClientEntityid")
                        .HasColumnType("int");

                    b.Property<string>("model")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("name")
                        .HasColumnType("varchar(255)");

                    b.Property<double?>("price")
                        .HasColumnType("double");

                    b.Property<int?>("stock")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("ClientEntityid");

                    b.ToTable("products");
                });

            modelBuilder.Entity("apicsharpfacturas.Models.Product", b =>
                {
                    b.HasOne("apicsharpfacturas.Models.ClientEntity", null)
                        .WithMany("products")
                        .HasForeignKey("ClientEntityid");
                });

            modelBuilder.Entity("apicsharpfacturas.Models.ClientEntity", b =>
                {
                    b.Navigation("products");
                });
#pragma warning restore 612, 618
        }
    }
}
